displayName=No Misclick Veng
author=Perry
description=Blocks recasting Vengeance while your current Vengeance is still active
tags=vengeance,lunar,misclick,pvm
# x-release-please-start-version
version=0.0.0
# x-release-please-end
plugins=com.nomisclickveng.NoMisclickVengPlugin
build=standard
