displayName=No Misclick Veng
author=Perry
description=Blocks recasting Vengeance while your current Vengeance is still active
tags=vengeance,lunar,misclick,pvm
version=
plugins=com.nomisclickveng.NoMisclickVengPlugin
build=standard
